FROM node:12.7-alpine
MAINTAINER "János Gats <gatsjanos@gmail.com>"

EXPOSE 80
ENV APP_HOME=/app

RUN mkdir -p ${APP_HOME}
WORKDIR ${APP_HOME}

COPY ./package.json ${APP_HOME}/
COPY ./package-lock.json ${APP_HOME}/
RUN npm install

COPY . ${APP_HOME}/.


ENV PATH ${APP_HOME}/node_modules/.bin:$PATH

ENTRYPOINT ["sh"]
# Only use '--disable-host-check' in localdev! It's a security flaw!
CMD ["-c", "ng serve --port 80 --host 0.0.0.0 --disable-host-check"]
